version: '3.8' 

services: 
  postgres: #  Название сервиса 
    image: postgres:15 #  Готовый образ из Docker Hub 
    environment: #  Переменные окружения (настройки для Postgres)
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: noteapp
    ports: # Проброс портов 
      - "5432:5432" #  Внешний порт:внутренний порт

  redis:
    image: redis:7
    ports:
      - "6379:6379"

#docker-compose up -d #  Открыть шкатулку и запустить всё в фоне
# docker-compose down  #  Закрыть шкатулку и убрать всё